repository:
  name: EditGuardainBot
  description: A simple telegarm bot
  homepage: https://t.me/TheTeamVivek
  private: true
  has_downloads: false
  default_branch: master

collaborators:
  - username: Vivekkumar-IN
    permission: admin