name: format codes

on:
  push:
    paths:
      - "**.go"
      - ".github/workflows/format.yml"
  workflow_dispatch:

jobs:
  format:
    uses: Vivekkumar-IN/assets/.github/workflows/format.yml@master
    with:
      language: go